SELECT DISTRINCT ?cid
            WHERE {
            OPTIONAL {?subject <http://127.0.0.1:8000/umwelt.owl#has_json_CID> ?object.}
            OPTIONAL {?subject  <http://127.0.0.1:8000/umwelt.owl#has_description> ?description.}
            OPTIONAL {?subject  <http://127.0.0.1:8000/umwelt.owl#has_tags> ?tags.}
            OPTIONAL {?subject  <http://127.0.0.1:8000/umwelt.owl#has_date> ?date.}
            
            BIND (STR(?subject) AS ?s) .
            BIND (STR(?tags) AS ?t) .
            BIND (STR(?description) AS ?d) .

            OPTIONAL { FILTER CONTAINS ( LCASE(?s) , ENCODE_FOR_URI('{}'))} .
            OPTIONAL { FILTER CONTAINS ( LCASE(?t) , ENCODE_FOR_URI('{}'))} .
            OPTIONAL { FILTER CONTAINS ( LCASE(?t) , ENCODE_FOR_URI('{}'))} .

            BIND (STRAFTER(STR(?object), 'http://127.0.0.1:8000/umwelt.owl#') AS ?cid) .

            }